# Generated by Django 4.2.5 on 2023-12-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('park_name', models.CharField(max_length=255)),
                ('park_location', models.CharField(max_length=255)),
                ('park_description', models.TextField()),
                ('inspector_name', models.CharField(max_length=255)),
                ('inspector_email', models.EmailField(max_length=254)),
                ('date_inspected', models.DateField()),
                ('inspection_notes', models.TextField()),
                ('is_passed', models.BooleanField(default=True)),
            ],
        ),
    ]
