# Generated by Django 4.2.7 on 2023-12-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('park_inspection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
